- name: Minimal web setup
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Nginx
      apt:
        name: nginx
        state: present
    - name: Ensure Nginx enabled and started
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Simple index
      copy:
        content: "<h1>Hello from {{ inventory_hostname }}!</h1>"
        dest: /var/www/html/index.html
